'use strict';

var _txt = {};
_txt.Products = {en:'Products'};
_txt.Categories = {en:'Categories'};
_txt.Orders = {en:'Orders'};
_txt.Buyers = {en:'Buyers'};
_txt.Settings = {en:'Settings'};
_txt.Home = {en:'Home'};
_txt.setting_shops = {en:'Shops'};
_txt.setting_no_shops = {en:'- No shops yet -'};
_txt.setting_shop_url = {en:'Shop url'};
_txt.setting_shop_urlprotocol = {en:'Shop url protocol'};
_txt.setting_shop_name = {en:'Shop name'};
_txt.setting_shop_name_example = {en:'My eShop'};
_txt.setting_shop_behawk = {en:'Shop behawk file name (by default: behawk)'};
_txt.setting_shop_cms_type = {en:'CMS'};
_txt.Save = {en:'Save'};
_txt.Add = {en:'Add'};
_txt.Add_shop = {en:'Add shop'};
_txt.Close = {en:'Close'};
_txt.Ok = {en:'Ok'};
_txt.Remove_question_title = {en:'<i class="icon-trash"></i> Remove?'};
_txt.Remove_question = {en:'Do you want to remove it?'};
_txt.stat_Incomes = {en:'Incomes'};
_txt.stat_Orders = {en:'Orders'};
_txt.Wrong_shop_url = {en:'Wrong shop url'};
_txt.Wrong_shop_url_text = {en:'Check your shop url in settings please'};

var lng = 'en';